" Vimrc"{{{

" Automatic reload vimrc on save
autocmd! bufwritepost .vimrc source %
" Disable unsafe commands in local .vimrc files
set secure
" Allow per-file settings via modeline
set modeline

"}}}
" Powerline"{{{

set rtp+=$HOME/.local/lib/python2.7/site-packages/powerline/bindings/vim/

"}}}
" Vundle"{{{

set rtp+=~/.vim/bundle/Vundle.vim"
call vundle#begin()

Plugin 'gmarik/Vundle.vim'

" Browsing {{{

Plugin 'Lokaltog/vim-easymotion'

Plugin 'scrooloose/nerdtree'

Plugin 'wesQ3/vim-windowswap'

Plugin 'kien/ctrlp.vim'

Plugin 'majutsushi/tagbar'

"}}}
" Editing {{{

" Dot repeat
Plugin 'tpope/vim-repeat'

" Auto format
Plugin 'Chiel92/vim-autoformat'

" Align
Plugin 'junegunn/vim-easy-align'

" Brace autoclose
Plugin 'Townk/vim-autoclose'

" Tags
Plugin 'xolox/vim-misc'
Plugin 'xolox/vim-easytags'

" Wrap
Plugin 'Soares/longline.vim'

"}}}
" SVC {{{

" Diff merging tool
Plugin 'sjl/splice.vim'
" Git wrapper
Plugin 'tpope/vim-fugitive'

"}}}
" CMD {{{

" unix cmd wrapper
Plugin 'tpope/vim-eunuch'

" interactive commands
Plugin 'oplatek/Conque-Shell'

"}}}
" Scala Interaction {{{

"Plugin 'megaannum/self'
"
"Plugin 'megaannum/forms'
"
"Plugin 'Shougo/vimproc'
"
"Plugin 'Shougo/vimshell'
"
"Plugin 'aemoncannon/ensime'
"
"Plugin 'megaannum/vimside'

" }}}
" Python Integration {{{

Plugin 'klen/python-mode'

Plugin 'vim-scripts/Efficient-python-folding'

"Plugin 'davidhalter/jedi-vim'

"}}}
" Julia Integration {{{

Plugin 'JuliaLang/julia-vim'

" }}}

Plugin 'drmingdrmer/xptemplate'

call vundle#end()

"}}}

filetype on
filetype plugin on
filetype indent on

" Load custom settings
source ~/.vim/startup/scripts.vim
source ~/.vim/startup/colors.vim
source ~/.vim/startup/mappings.vim
source ~/.vim/startup/settings.vim

" Plugin Configuration {{{

" NERDTree
let NERDTreeMinimalUI=1
let NERDTreeDirArrows=1
let NERDTreeAutoCenter=1

" EasyMotion

" Disable default mappings
let g:EasyMotion_do_mapping = 0
" Turn on case sensitive feature
let g:EasyMotion_smartcase = 1
" Key settings
let g:EasyMotion_keys='hklyuiopnm,qwertzxcvbasdgjf;'


" Vim Window Swap
" Prevent default bindings
let g:windowswap_map_keys = 0

" CtrlP
let g:ctrlp_max_height=30
set wildignore+=*.pyc
set wildignore+=*_build/*
set wildignore+=*/coverage/*


" Python Mode
let g:pymode_doc = 1
let g:pymode_motion = 1
let g:pymode_lint = 1
let g:pymode_lint_checker = ['pyflakes', 'pep8']
let g:pymode_rope = 1
let g:pymode_rope_goto_definition_cmd = 'new'
" Pylint check on save
let g:pymode_lint_write = 1
" Support virtualenv
let g:pymode_virtualenv = 1
" Enable breakpoints plugin
let g:pymode_breakpoint = 1
" Syntax highlighting
let g:pymode_syntax = 1
let g:pymode_syntax_all = 1
let g:pymode_syntax_builtin_objs = 0
let g:pymode_syntax_builtin_funcs = 0
let g:pymode_syntax_indent_errors = g:pymode_syntax_all
let g:pymode_syntax_space_errors = g:pymode_syntax_all


" Efficient python folding
set nofoldenable

" ConqueTerm
let g:ConqueTerm_Color = 1
let g:ConqueTerm_FastMode = 0

" }}}
