" Vimrc"{{{

" Automatic reload vimrc on save
autocmd! bufwritepost .vimrc source %
" Disable unsafe commands in local .vimrc files
set secure
" Allow per-file settings via modeline
set modeline

"}}}
" Powerline"{{{

set rtp+=$HOME/.local/lib/python2.7/site-packages/powerline/bindings/vim/

"}}}
" Vundle "{{{

set rtp+=~/.vim/bundle/Vundle.vim"
call vundle#begin()

Plugin 'gmarik/Vundle.vim'

" Browsing
Plugin 'Lokaltog/vim-easymotion'
Plugin 'scrooloose/nerdtree'
Plugin 'wesQ3/vim-windowswap'
Plugin 'kien/ctrlp.vim'
Plugin 'majutsushi/tagbar'

" Editing
Plugin 'tpope/vim-repeat'                  "  Dot Repeat
Plugin 'Chiel92/vim-autoformat'            "  Auto Format
Plugin 'junegunn/vim-easy-align'           "  Auto Align
Plugin 'Townk/vim-autoclose'               "  Auto Brace Close
Plugin 'xolox/vim-misc'
Plugin 'xolox/vim-easytags'                "  Tags
Plugin 'Soares/longline.vim'               "  Wrapping
Plugin 'drmingdrmer/xptemplate'            "  Template

" Git
Plugin 'sjl/splice.vim'                    "  Git Diff Merging Tool
Plugin 'tpope/vim-fugitive'                "  Git Wrapper

" Terminal
Plugin 'tpope/vim-eunuch'                  "  Terminal Wrapper
Plugin 'oplatek/Conque-Shell'              "  Terminal Embedding

" Python
Plugin 'klen/python-mode'
Plugin 'vim-scripts/Efficient-python-folding'
"Plugin 'davidhalter/jedi-vim'

" Julia
Plugin 'JuliaLang/julia-vim'

call vundle#end()

"}}}

filetype on
filetype plugin on
filetype indent on

" Load custom settings
source ~/.vim/custom/scripts.vim
source ~/.vim/custom/colors.vim
source ~/.vim/custom/mappings.vim
source ~/.vim/custom/settings.vim

" Load custom plugin settings
source ~/.vim/custom/plugins/nerdtree.vim
source ~/.vim/custom/plugins/easymotion.vim
source ~/.vim/custom/plugins/windowswap.vim
source ~/.vim/custom/plugins/ctrlp.vim

source ~/.vim/custom/plugins/conqueterm.vim

source ~/.vim/custom/plugins/python-mode.vim
source ~/.vim/custom/plugins/efficient-python-folding.vim
